### PR TITLE
15 get playlist index end point

### PR DESCRIPTION
**Pull request by zingsurfer**
GET /api/v1/playlists

Returns all the playlists in the database along with their associated songs

If successful, this request will return a response in the following format:
```
[
    {
        "id": 1,
        "playlist_name": "Favorite songs of all time",
        "songs": [
          {
            "id": 1,
            "name": "We Will Rock You",
            "artist_name": "Queen"
            "genre": "Rock",
            "song_rating": 88
          },
          {
            "id": 2,
            "name": "Careless Whisper",
            "artist_name": "George Michael"
            "genre": "Pop",
            "song_rating": 93
          }
        ]
    },
    {
        "id": 2,
        "name": "Other amazing songs",
        "songs": [
          {
            "id": 1,
            "name": "We Will Rock You",
            "artist_name": "Queen"
            "genre": "Rock",
            "song_rating": 88
          },
          {
            "id": 2,
            "name": "Careless Whisper",
            "artist_name": "George Michael"
            "genre": "Pop",
            "song_rating": 93
          },
        ]
    },
]
```

### CODE REVIEW

**Comment by abdullaqudrat** [comment]
Hi @ameseee, we are trying to build a hash for our GET playlists route so it can respond with playlists and the songs associated with the playlist from line 118 to 130 on the server.js file. Can you take a peek and see if you can point us in the right direction. Thanks!

**Comment by ameseee** [comment]
Hi @abdullaqudrat! Do you have what you want in the `playlist` variable on line 120? How about the `final`? I would go down the path using pry.it/console.log to determine where you are 'losing' (if you are) your data. I can pair for a few minutes during lunch tomorrow, let me know!!

**Comment by zingsurfer** [comment]
Thanks @ameseee! We will look in to those things and let you know if we're still stuck.

**Comment by zingsurfer** [comment]
Hi @ameseee, just wanted to give you an update. Abdulla & I were able to successfully retrieved all the data for this endpoint! I have submitted a PR for it [here](https://github.com/abdullaqudrat/play_full_stack_api/pull/9).

**Pull request closed without merging**
